const etudiants = [
  {
    "id": 1,
    "nom": "Gauthier",
    "prenom": "Léa",
    "photo_profil": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&h=400&fit=crop",
    "filiere": "Communication Digitale",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2025",
    "commentaire": "Une ambiance incroyable et des intervenants très pros. Je recommande vivement !",
    "whatsapp": "https://wa.me/33611223301",
    "linkedin": "https://www.linkedin.com/in/lea-gauthier-com",
    "instagram": "https://www.instagram.com/lea_gth"
  },
  {
    "id": 2,
    "nom": "Masson",
    "prenom": "Lucas",
    "photo_profil": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&h=400&fit=crop",
    "filiere": "Ingénierie",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2023",
    "commentaire": "Grâce à la formation, j'ai trouvé mon premier job en moins de deux mois. Le réseau alumni est top.",
    "whatsapp": "https://wa.me/33611223302",
    "linkedin": "https://www.linkedin.com/in/lucas-masson-ing",
    "instagram": "https://www.instagram.com/lucas_m_dev"
  },
  {
    "id": 3,
    "nom": "Belkacem",
    "prenom": "Yasmine",
    "photo_profil": "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&h=400&fit=crop",
    "filiere": "Droit International",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2026",
    "commentaire": "Le campus est moderne et très bien situé. Les cours de droit sont passionnants.",
    "whatsapp": "https://wa.me/33611223303",
    "linkedin": "https://www.linkedin.com/in/yasmine-b-law",
    "instagram": "https://www.instagram.com/yas_lawyer"
  },
  {
    "id": 4,
    "nom": "Rivière",
    "prenom": "Hugo",
    "photo_profil": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&h=400&fit=crop",
    "filiere": "Architecture",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2022",
    "commentaire": "Les projets de groupe m'ont appris à travailler en équipe comme en agence. Un vrai plus.",
    "whatsapp": "https://wa.me/33611223304",
    "linkedin": "https://www.linkedin.com/in/hugo-riviere-archi",
    "instagram": "https://www.instagram.com/hugo_builds"
  },
  {
    "id": 5,
    "nom": "Moreau",
    "prenom": "Chloé",
    "photo_profil": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&h=400&fit=crop",
    "filiere": "Médecine",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2027",
    "commentaire": "Les équipements de simulation sont de dernière génération, c'est idéal pour s'exercer.",
    "whatsapp": "https://wa.me/33611223305",
    "linkedin": "https://www.linkedin.com/in/chloe-moreau-med",
    "instagram": "https://www.instagram.com/chloe_doc"
  },
  {
    "id": 6,
    "nom": "Diallo",
    "prenom": "Amadou",
    "photo_profil": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&h=400&fit=crop",
    "filiere": "Informatique",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2025",
    "commentaire": "On a accès à beaucoup de ressources en ligne et le tutorat entre étudiants aide vraiment.",
    "whatsapp": "https://wa.me/33611223306",
    "linkedin": "https://www.linkedin.com/in/amadou-diallo-it",
    "instagram": "https://www.instagram.com/amadou_code"
  },
  {
    "id": 7,
    "nom": "Petit",
    "prenom": "Manon",
    "photo_profil": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&h=400&fit=crop",
    "filiere": "Design Graphique",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2023",
    "commentaire": "La liberté créative que l'on nous laisse est exceptionnelle. J'ai pu développer mon propre style.",
    "whatsapp": "https://wa.me/33611223307",
    "linkedin": "https://www.linkedin.com/in/manon-petit-design",
    "instagram": "https://www.instagram.com/manon_pixels"
  },
  {
    "id": 8,
    "nom": "Lefebvre",
    "prenom": "Théo",
    "photo_profil": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&h=400&fit=crop",
    "filiere": "Finance",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2024",
    "commentaire": "Le rythme est soutenu mais l'entraide entre élèves permet de ne jamais lâcher.",
    "whatsapp": "https://wa.me/33611223308",
    "linkedin": "https://www.linkedin.com/in/theo-lefebvre-fin",
    "instagram": "https://www.instagram.com/theo_finance"
  },
  {
    "id": 9,
    "nom": "Martinez",
    "prenom": "Sofia",
    "photo_profil": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=400&h=400&fit=crop",
    "filiere": "Langues Étrangères",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2021",
    "commentaire": "Les échanges internationaux proposés sont un vrai tremplin pour la suite de la carrière.",
    "whatsapp": "https://wa.me/33611223309",
    "linkedin": "https://www.linkedin.com/in/sofia-martinez-trad",
    "instagram": "https://www.instagram.com/sofia_polyglot"
  },
  {
    "id": 10,
    "nom": "Andre",
    "prenom": "Enzo",
    "photo_profil": "https://images.unsplash.com/photo-1488161628813-04466f872be2?q=80&w=400&h=400&fit=crop",
    "filiere": "Sport Études",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2025",
    "commentaire": "L'école permet de concilier parfaitement le sport de haut niveau et les études.",
    "whatsapp": "https://wa.me/33611223310",
    "linkedin": "https://www.linkedin.com/in/enzo-andre-sport",
    "instagram": "https://www.instagram.com/enzo_coach"
  },
  {
    "id": 11,
    "nom": "Lemoine",
    "prenom": "Bastien",
    "photo_profil": "https://images.unsplash.com/photo-1503910321444-85d9851b65d5?q=80&w=400&h=400&fit=crop",
    "filiere": "Jeux Vidéo",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2023",
    "commentaire": "Des profs passionnés qui viennent de l'industrie. C'est du concret dès le premier jour.",
    "whatsapp": "https://wa.me/33611223311",
    "linkedin": "https://www.linkedin.com/in/bastien-lemoine-game",
    "instagram": "https://www.instagram.com/bast_gaming"
  },
  {
    "id": 12,
    "nom": "Rousseau",
    "prenom": "Manon",
    "photo_profil": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&h=400&fit=crop",
    "filiere": "Journalisme",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2024",
    "commentaire": "La mise à disposition d'un studio radio et télé est géniale pour nos exercices pratiques.",
    "whatsapp": "https://wa.me/33611223312",
    "linkedin": "https://www.linkedin.com/in/manon-rousseau-press",
    "instagram": "https://www.instagram.com/manon_reporter"
  },
  {
    "id": 13,
    "nom": "Girard",
    "prenom": "Nathan",
    "photo_profil": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=400&h=400&fit=crop",
    "filiere": "Intelligence Artificielle",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2026",
    "commentaire": "On travaille sur des vrais cas d'entreprises, c'est très motivant et formateur.",
    "whatsapp": "https://wa.me/33611223313",
    "linkedin": "https://www.linkedin.com/in/nathan-girard-ai",
    "instagram": "https://www.instagram.com/nathan_dev"
  },
  {
    "id": 14,
    "nom": "Fontaine",
    "prenom": "Sarah",
    "photo_profil": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=400&h=400&fit=crop",
    "filiere": "Vétérinaire",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2022",
    "commentaire": "L'accompagnement post-diplôme m'a aidée à ouvrir mon propre cabinet.",
    "whatsapp": "https://wa.me/33611223314",
    "linkedin": "https://www.linkedin.com/in/sarah-fontaine-vet",
    "instagram": "https://www.instagram.com/sarah_veto"
  },
  {
    "id": 15,
    "nom": "Bonnet",
    "prenom": "Jules",
    "photo_profil": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&h=400&fit=crop",
    "filiere": "Aéronautique",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2025",
    "commentaire": "Les partenariats avec les grands groupes industriels sont un vrai point fort.",
    "whatsapp": "https://wa.me/33611223315",
    "linkedin": "https://www.linkedin.com/in/jules-bonnet-aero",
    "instagram": "https://www.instagram.com/jules_fly"
  },
  {
    "id": 16,
    "nom": "Dupuis",
    "prenom": "Zoé",
    "photo_profil": "https://images.unsplash.com/photo-1548142813-c348350df52b?q=80&w=400&h=400&fit=crop",
    "filiere": "Marketing Luxe",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2023",
    "commentaire": "Le réseau de contacts dans le monde du luxe est très puissant ici.",
    "whatsapp": "https://wa.me/33611223316",
    "linkedin": "https://www.linkedin.com/in/zoe-dupuis-luxury",
    "instagram": "https://www.instagram.com/zoe_luxe"
  },
  {
    "id": 17,
    "nom": "Muller",
    "prenom": "Maxime",
    "photo_profil": "https://images.unsplash.com/photo-1504257406239-8b51f5634725?q=80&w=400&h=400&fit=crop",
    "filiere": "Développement Web",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2025",
    "commentaire": "J'apprends plus en un semestre ici qu'en deux ans ailleurs. Très axé pratique.",
    "whatsapp": "https://wa.me/33611223317",
    "linkedin": "https://www.linkedin.com/in/maxime-muller-web",
    "instagram": "https://www.instagram.com/max_code"
  },
  {
    "id": 18,
    "nom": "Boyer",
    "prenom": "Eva",
    "photo_profil": "https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=400&h=400&fit=crop",
    "filiere": "Histoire de l'art",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2024",
    "commentaire": "Les visites de musées organisées chaque semaine enrichissent énormément notre formation.",
    "whatsapp": "https://wa.me/33611223318",
    "linkedin": "https://www.linkedin.com/in/eva-boyer-art",
    "instagram": "https://www.instagram.com/eva_museum"
  },
  {
    "id": 19,
    "nom": "Hubert",
    "prenom": "Yanis",
    "photo_profil": "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=400&h=400&fit=crop",
    "filiere": "Sport Management",
    "ecole": "Studi Campus",
    "status": "Diplômé",
    "promotion": "2023",
    "commentaire": "Une école qui a une vraie vision. J'ai pu monter mon projet de start-up grâce à eux.",
    "whatsapp": "https://wa.me/33611223319",
    "linkedin": "https://www.linkedin.com/in/yanis-hubert-sport",
    "instagram": "https://www.instagram.com/yanis_coach"
  },
  {
    "id": 20,
    "nom": "Picard",
    "prenom": "Juliette",
    "photo_profil": "https://images.unsplash.com/photo-1485178575877-1a13bf489dee?q=80&w=400&h=400&fit=crop",
    "filiere": "Relations Internationales",
    "ecole": "Studi Campus",
    "status": "Étudiant",
    "promotion": "2025",
    "commentaire": "La diversité des profils sur le campus est une richesse incroyable au quotidien.",
    "whatsapp": "https://wa.me/33611223320",
    "linkedin": "https://www.linkedin.com/in/juliette-picard-world",
    "instagram": "https://www.instagram.com/juliette_diplomacy"
  }
];